In [24]:
import numpy as np #numpy kütüphanesini np olarak ekler
dizi1=np.array([1,2,3])
dizi2=np.array(["elma","armut","vişne"])

In [25]:
dizi1

array([1, 2, 3])

In [26]:
dizi2

array(['elma', 'armut', 'vişne'], dtype='<U5')

In [20]:
np.array([1,2,3])#NumPy dizisi oluşturmak için 

array([1, 2, 3])

In [22]:
dizi=np.array([1,2,3,3.14],dtype=int)#NumPy dizilerini tanımlama sırasında dizideki tüm elemanları tek tipe dönüştürme işlemi
gerçekleştirilebilir.
dizi

array([1, 2, 3, 3])

In [27]:
birboyut=np.array([1,2,3])
birboyut

array([1, 2, 3])

In [28]:
ikiboyut = np.array([[1,2,3], [4,5,6]])#İki boyutlu dizi oluşturmak için
ikiboyut

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
ucboyut= np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])#Üç boyutlu dizi oluşturmak için
ucboyut

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])