**Numpy Dizi İşlemler**

In [5]:
import numpy as np #numpy kütüphanesini np takma adı ile projeye dahil ediyoruz

In [6]:
dizi = np.full((4, 3), 5)#4 satır ve 3 sütundan oluşan, her elemanı 5 olan bir NumPy dizisi oluşturur.
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [7]:
np.array([1,2,3])#yeni bir numpy dizisi oluşturur

array([1, 2, 3])

In [8]:
dizi=np.array(["elma","erik","iğde"])#oluşturduğumuz diziyi bir değişkene aktarıyoruz

In [11]:
dizi

array(['elma', 'erik', 'iğde'], dtype='<U4')

In [12]:
dizi=np.array([1,2,3])# NumPy kullanarak 1, 2 ve 3 elemanlarından oluşan bir dizi (veya array) oluşturur.  

In [13]:
dizi

array([1, 2, 3])

In [19]:
dizi=np.array([1,2,3.14] , dtype=int)

In [20]:
dizi

array([1, 2, 3])

In [18]:
dizi.dtype #dizinin değişken türünü verir.numpy dizilerinde elemanların hepsi aynı türdendir

dtype('float64')

**Numpy ile fark boyutları dizi oluşturma**

In [21]:
#bir boyutlu dizi oluşturma
birboyut=np.array([1,2,3,4])
#iki boyutlu dizi oluşturma
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [22]:
birboyut

array([1, 2, 3, 4])

In [23]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Numpy yer tutucular**

In [24]:
np.zeros(7)#7 sıfırdan oluşan tek boyutlu dizi oluşturur

array([0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((2,3),dtype=int)#* sıfırdan oluşan 2 boyutlu int dizi oluşturur

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
np.ones(3)#3 elemanlı bir dizi oluşturur ve bu elemanların her biri 1.0 değerine sahiptir.

array([1., 1., 1.])

In [27]:
np.full((4,3),5)#5sayısından oluşan 2*3 lük dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [28]:
np.arange(2,22,5)#başlangıç,bitiş ve artış değerine göre dizi oluşturma

array([ 2,  7, 12, 17])

In [29]:
np.linspace(2,10,num=7)#başlangıç ve bitiş değer aralığında belirtilen miktarda eşit aralık 

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [30]:
np.random.randint(0,10,5)#0-10 aralığında rastgele 5 sayıdan oluşan bir boyutlu dizi

array([1, 7, 2, 3, 6])

In [32]:
np.random.randint(0,10,(5,2))#0-10 aralığında 5*2 rastgele sayıdan oluşan 2 boyutlu dizi

array([[0, 0],
       [7, 7],
       [4, 1],
       [1, 9],
       [8, 0]])

**Diziler ile ilgili işlemler**

In [33]:
#dizilerin eleman sayısını öğrenmek için shape komutu kullanılır
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

(3, 4)

In [34]:
#ndim dizi boyutunu öğrenmek için kullanılır
dizi.ndim

2

In [35]:
#size dizideki toplam eleman sayısını gösterir
dizi.size

12

In [37]:
dizi.itemsize#dizideki her bir elemanın bayt cinsinden değerini verir

4

In [38]:
dizi = np.random.randint(0, 100,(5, 7))#5 satır 7 sütun olacak şekilde rastgele sayılardan oluşan int turunde bir dizi

In [39]:
dizi

array([[40, 84, 85, 75, 65, 57, 62],
       [ 1, 73, 30, 73, 50, 33, 57],
       [53, 70, 49, 98, 24, 57, 36],
       [46, 87, 72, 23, 53, 84, 39],
       [70, 68, 70, 49, 76, 27, 24]])